### ISSUE TITLE
Prefer actual methods over `__callStatic()`

### ISSUE THREAD

**Issue by schlessera** [felixarntz/wp-psr-cache#8]
The magic method `__callStatic()` is nice as a dynamic fallback for classes where you don't know upfront what methods to use.

However, in the case of your ObjectService, I would recommend adding all the ObjectCache methods directly to the facade, as the `__callStatic()` magic method comes at a steep overhead cost. You can keep it in for fallbacks in case someone uses more complex object cache implementations, but as this code is performance-sensitive, it should not be used for the default code paths.

**Comment by felixarntz** [comment]
That makes sense, thanks! Depending on the discussion outcome of #7, which will determine whether this is needed at all, I'll add those methods.

**Comment by felixarntz** [comment]
This is no longer an issue after #7.
